use super::*;
use ratatui::widgets::TableState;
use serde_json::Value;
use std::collections::HashMap;

pub struct ViewerState {
    /// dbField -> type ("seconds" or "date")
    pub date_fields: HashMap<String, String>,
    /// dbField -> exp (expression field name)
    pub field_exp_map: HashMap<String, String>,
    /// dbField -> friendlyName
    pub field_friendly_map: HashMap<String, String>,
    pub sessions: Vec<Value>,
    pub sessions_total: u64,
    pub sessions_filtered: u64,
    pub session_fields: Vec<String>,
    pub columns: Vec<ColumnDef>,
    pub saved_layouts: Vec<SavedLayout>,
    pub show_column_editor: bool,
    pub column_editor_selected: usize,
    pub column_editor_mode: ColumnEditorMode,
    pub column_editor_available: Vec<ColumnEditorItem>,
    pub column_editor_filter: String,
    pub column_editor_filter_cursor: usize,
    pub show_layout_popup: bool,
    pub layout_popup_mode: LayoutPopupMode,
    pub layout_popup_selected: usize,
    pub layout_save_name: String,
    pub layout_save_cursor: usize,
    pub layout_delete_name: String,
    pub layout_filter: String,
    pub layout_filter_cursor: usize,
    pub active_view: Option<String>,
    /// view name for display
    pub active_view_name: Option<String>,
    pub saved_views: Vec<crate::api::ArkimeView>,
    pub show_view_popup: bool,
    pub view_popup_mode: ViewPopupMode,
    pub view_popup_selected: usize,
    pub view_save_name: String,
    pub view_save_cursor: usize,
    pub view_save_columns: bool,
    pub view_delete_id: String,
    pub view_delete_name: String,
    pub view_filter: String,
    pub view_filter_cursor: usize,
    pub view_filter_active: bool,
    pub page_start: u64,
    pub page_size: u64,
    pub selected_session: usize,
    pub table_state: TableState,
    pub session_view: SessionView,
    pub session_detail: Option<SessionDetail>,
    pub detail_action_menu: Option<DetailActionMenu>,
    pub packets_view: Option<crate::api::PacketsData>,
    pub packets_scroll: u16,
    pub packets_raw: bool,
    pub packets_line: LineMode,
    pub pending_packets_fetch: bool,
    pub pending_summary_fetch: bool,
    pub pending_stats_fetch: bool,
    pub packets_node_pending: String,
    pub packets_id_pending: String,
    pub packets_total_pending: u64,
    pub sort_column: usize,
    pub sort_desc: bool,
    pub graph_size: GraphSize,
    pub graph_type: GraphType,
    pub graph_data: Option<crate::api::GraphData>,
    /// Stats tab state
    pub stats_tab: StatsTab,
    pub stats_data: Vec<Value>,
    pub stats_total: u64,
    pub stats_filtered: u64,
    pub stats_filter: String,
    pub stats_filter_edit: String,
    pub stats_selected: usize,
    pub stats_table_state: TableState,
    pub stats_view: StatsView,
    pub stats_detail: Option<StatsDetail>,
    pub stats_sort_column: usize,
    pub stats_sort_desc: bool,
    pub stats_last_refresh: std::time::Instant,
    /// Per-tab dynamic stats columns
    pub stats_columns: [Vec<StatsColumnDef>; 5],
    /// Whether user state has been loaded for each stats sub-tab
    pub stats_state_loaded: [bool; 5],
    /// Stats column editor
    pub stats_show_column_editor: bool,
    pub stats_column_editor_selected: usize,
    pub stats_column_editor_mode: ColumnEditorMode,
    pub stats_column_editor_items: Vec<StatsColumnEditorItem>,
    pub stats_column_editor_filter: String,
    pub stats_column_editor_filter_cursor: usize,
    /// Stats layout popup (shareables)
    pub stats_show_layout_popup: bool,
    pub stats_layout_popup_mode: LayoutPopupMode,
    pub stats_layout_popup_selected: usize,
    pub stats_saved_shareables: Vec<SavedShareable>,
    pub stats_layout_save_name: String,
    pub stats_layout_save_cursor: usize,
    pub stats_layout_delete_name: String,
    pub stats_layout_filter: String,
    pub stats_layout_filter_cursor: usize,
    /// DB Shards state (custom grid view, not table-based)
    pub shards_data: Value,
    pub shards_nodes: Vec<String>,
    pub shards_indices: Vec<String>,
    pub shards_show: ShardsShow,
    pub shards_selected_row: usize,
    pub shards_hscroll: usize,
    pub shards_loaded: bool,
    pub shards_detail: Option<StatsDetail>,
    pub shards_sub_detail: Option<StatsDetail>,
    /// Recovery show mode: false = "notdone" (active only), true = "all"
    pub recovery_show_all: bool,
    /// Capture Graphs state
    pub cg_metric_index: usize,
    pub cg_interval: CaptureGraphInterval,
    pub cg_hide: CaptureGraphHide,
    pub cg_nodes: Vec<CaptureGraphNodeData>,
    pub cg_scroll: usize,
    pub cg_show_metric_popup: bool,
    pub cg_metric_popup_selected: usize,
    pub cg_metric_popup_filter: String,
    pub cg_metric_popup_filter_cursor: usize,
    pub cg_loaded: bool,
    /// Files tab state
    pub files_data: Vec<Value>,
    pub files_total: u64,
    pub files_filtered: u64,
    pub files_filter: String,
    pub files_filter_edit: String,
    pub files_selected: usize,
    pub files_table_state: TableState,
    pub files_sort_column: usize,
    pub files_sort_desc: bool,
    pub files_page_start: usize,
    pub files_page_size: usize,
    pub files_columns: Vec<StatsColumnDef>,
    /// Whether user state has been loaded for files tab
    pub files_state_loaded: bool,
    /// Files column editor
    pub files_show_column_editor: bool,
    pub files_column_editor_selected: usize,
    pub files_column_editor_mode: ColumnEditorMode,
    pub files_column_editor_items: Vec<StatsColumnEditorItem>,
    pub files_column_editor_filter: String,
    pub files_column_editor_filter_cursor: usize,
    /// Files layout popup (shareables)
    pub files_show_layout_popup: bool,
    pub files_layout_popup_mode: LayoutPopupMode,
    pub files_layout_popup_selected: usize,
    pub files_saved_shareables: Vec<SavedShareable>,
    pub files_layout_save_name: String,
    pub files_layout_save_cursor: usize,
    pub files_layout_delete_name: String,
    pub files_layout_filter: String,
    pub files_layout_filter_cursor: usize,
    pub files_view: StatsView,
    pub files_detail: Option<StatsDetail>,
    /// Arkime (Summary) tab state
    pub all_fields: Vec<crate::api::ArkimeField>,
    pub summary_field: String,
    pub summary_data: Vec<crate::api::SummaryItem>,
    pub summary_metric: SummaryMetric,
    pub summary_selected: usize,
    pub summary_table_state: TableState,
    pub summary_sort: SummarySort,
    pub summary_sort_desc: bool,
    pub field_filter: String,
    pub field_filter_cursor: usize,
    pub field_filter_selected: usize,
}

impl Default for ViewerState {
    fn default() -> Self {
        Self {
            date_fields: HashMap::new(),
            field_exp_map: HashMap::new(),
            field_friendly_map: HashMap::new(),
            sessions: Vec::new(),
            sessions_total: 0,
            sessions_filtered: 0,
            session_fields: vec![
            "ipProtocol".into(),
            "firstPacket".into(),
            "lastPacket".into(),
            "source.ip".into(),
            "source.port".into(),
            "destination.ip".into(),
            "destination.port".into(),
            "protocol".into(),
            "source.packets".into(),
            "destination.packets".into(),
            "source.bytes".into(),
            "destination.bytes".into(),
            ],
            columns: default_columns(),
            saved_layouts: Vec::new(),
            show_column_editor: false,
            column_editor_selected: 0,
            column_editor_mode: ColumnEditorMode::Browse,
            column_editor_available: Vec::new(),
            column_editor_filter: String::new(),
            column_editor_filter_cursor: 0,
            show_layout_popup: false,
            layout_popup_mode: LayoutPopupMode::List,
            layout_popup_selected: 0,
            layout_save_name: String::new(),
            layout_save_cursor: 0,
            layout_delete_name: String::new(),
            layout_filter: String::new(),
            layout_filter_cursor: 0,
            active_view: None,
            active_view_name: None,
            saved_views: Vec::new(),
            show_view_popup: false,
            view_popup_mode: ViewPopupMode::List,
            view_popup_selected: 0,
            view_save_name: String::new(),
            view_save_cursor: 0,
            view_save_columns: false,
            view_delete_id: String::new(),
            view_delete_name: String::new(),
            view_filter: String::new(),
            view_filter_cursor: 0,
            view_filter_active: false,
            page_start: 0,
            page_size: 100,
            selected_session: 0,
            table_state: TableState::default().with_selected(0),
            session_view: SessionView::List,
            session_detail: None,
            detail_action_menu: None,
            packets_view: None,
            packets_scroll: 0,
            packets_raw: false,
            packets_line: LineMode::Hex,
            pending_packets_fetch: false,
            pending_summary_fetch: false,
            pending_stats_fetch: false,
            packets_node_pending: String::new(),
            packets_id_pending: String::new(),
            packets_total_pending: 0,
            sort_column: 2,
            sort_desc: true,
            graph_size: GraphSize::Off,
            graph_type: GraphType::Sessions,
            graph_data: None,
            // Stats tab state
            stats_tab: StatsTab::Capture,
            stats_data: Vec::new(),
            stats_total: 0,
            stats_filtered: 0,
            stats_filter: String::new(),
            stats_filter_edit: String::new(),
            stats_selected: 0,
            stats_table_state: TableState::default().with_selected(0),
            stats_view: StatsView::List,
            stats_detail: None,
            stats_sort_column: 0,
            stats_sort_desc: false,
            stats_last_refresh: std::time::Instant::now(),
            stats_columns: [
            stats_columns_from_fields(&capture_default_fields(), &capture_all_columns()),
            stats_columns_from_fields(&esnodes_default_fields(), &esnodes_all_columns()),
            stats_columns_from_fields(&esindices_default_fields(), &esindices_all_columns()),
            stats_columns_from_fields(&estasks_default_fields(), &estasks_all_columns()),
            stats_columns_from_fields(&esrecovery_default_fields(), &esrecovery_all_columns()),
            ],
            stats_state_loaded: [false; 5],
            stats_show_column_editor: false,
            stats_column_editor_selected: 0,
            stats_column_editor_mode: ColumnEditorMode::Browse,
            stats_column_editor_items: Vec::new(),
            stats_column_editor_filter: String::new(),
            stats_column_editor_filter_cursor: 0,
            stats_show_layout_popup: false,
            stats_layout_popup_mode: LayoutPopupMode::List,
            stats_layout_popup_selected: 0,
            stats_saved_shareables: Vec::new(),
            stats_layout_save_name: String::new(),
            stats_layout_save_cursor: 0,
            stats_layout_delete_name: String::new(),
            stats_layout_filter: String::new(),
            stats_layout_filter_cursor: 0,
            // DB Shards
            shards_data: Value::Null,
            shards_nodes: Vec::new(),
            shards_indices: Vec::new(),
            shards_show: ShardsShow::NotStarted,
            shards_selected_row: 0,
            shards_hscroll: 0,
            shards_loaded: false,
            shards_detail: None,
            shards_sub_detail: None,
            recovery_show_all: false,
            // Capture Graphs
            cg_metric_index: 0,
            cg_interval: CaptureGraphInterval::FiveSec,
            cg_hide: CaptureGraphHide::None,
            cg_nodes: Vec::new(),
            cg_scroll: 0,
            cg_show_metric_popup: false,
            cg_metric_popup_selected: 0,
            cg_metric_popup_filter: String::new(),
            cg_metric_popup_filter_cursor: 0,
            cg_loaded: false,
            // Files tab
            files_data: Vec::new(),
            files_total: 0,
            files_filtered: 0,
            files_filter: String::new(),
            files_filter_edit: String::new(),
            files_selected: 0,
            files_table_state: TableState::default(),
            files_sort_column: 0,
            files_sort_desc: false,
            files_page_start: 0,
            files_page_size: 100,
            files_columns: stats_columns_from_fields(&files_default_fields(), &files_all_columns()),
            files_state_loaded: false,
            files_show_column_editor: false,
            files_column_editor_selected: 0,
            files_column_editor_mode: ColumnEditorMode::Browse,
            files_column_editor_items: Vec::new(),
            files_column_editor_filter: String::new(),
            files_column_editor_filter_cursor: 0,
            files_show_layout_popup: false,
            files_layout_popup_mode: LayoutPopupMode::List,
            files_layout_popup_selected: 0,
            files_saved_shareables: Vec::new(),
            files_layout_save_name: String::new(),
            files_layout_save_cursor: 0,
            files_layout_delete_name: String::new(),
            files_layout_filter: String::new(),
            files_layout_filter_cursor: 0,
            files_view: StatsView::List,
            files_detail: None,
            // Arkime (Summary) tab state
            all_fields: Vec::new(),
            summary_field: String::new(),
            summary_data: Vec::new(),
            summary_metric: SummaryMetric::Sessions,
            summary_selected: 0,
            summary_table_state: TableState::default().with_selected(0),
            summary_sort: SummarySort::Sessions,
            summary_sort_desc: true,
            field_filter: String::new(),
            field_filter_cursor: 0,
            field_filter_selected: 0,
        }
    }
}
